
import "./globals.css";
import { Inter } from "next/font/google";
import PostsContextProvider from "@/context/context";
import NavBar from "@/components/Navbar";
import { useEffect, useState } from "react";
import Loading from "@/components/LoadingPosts";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Posts App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <PostsContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </PostsContextProvider>
  );
}
